#!/usr/bin/expect -f


for {set i 0} {$i < 6} {incr i 1} {
  spawn ssh socialsoul@socialsoul${i}.local
  expect "assword:"
  send "soulmate\r"
  expect "$ " 
  send "sudo shutdown -h now\r" 
  expect "assword:"
  send "soulmate\r"
  expect "$ "
  send "exit\r"
}


spawn ssh socialsoulserver.local
expect "assword:"
send "soulmate\r"
expect "$ " 
send "sudo shutdown -h now\r"
expect "$ "
send "exit\r"