#!/usr/bin/expect -f


for {set i 0} {$i < 5} {incr i 1} {
  spawn ssh socialsoul@socialsoul${i}.local
  expect "assword:"
  send "soulmate\r"
  expect "$ " 
  send "osascript ~/Desktop/start-social-soul-screen.scpt &\r" 
  expect "$ " 
  send "exit\r"
}


spawn ssh socialsoulserver@socialsoulserver.local
expect "assword:"
send "soulmate\r"
expect "$ " 
send "osascript ~/socialsoul/extra/start-social-soul-exit.scpt &\r" 
expect "$ " 
send "exit\r"
